### ISSUE TITLE
t_depth need to be updated

### ISSUE THREAD

**Issue by artonmarton** [morinlab/lab_scripts#7]
Hello,
When running augment_maf.py for trios(N/T1/T2) the t_depth data in the generated mafs would be the same as the first maf file in the command no matter what the bam files is (T1 or T2). So if we want to generate aug.maf for T2 and use the T1 maf first in the command, that will give us t_depth data of T1 instead of T2 . Apparently the script does not update the t_depth information in the maf file and just use the present data in the first maf file.

Thanks,
Arezoo

**Comment by brunogrande** [comment]
I will fix this bug by simply adding up the ref_count and alt_count columns.

**Comment by artonmarton** [comment]
Sounds good, if the ref_count and alt_count are accurate then that is a
very good and straight forward solution.
